from __future__ import annotations

from datetime import datetime, timedelta
import hashlib
import json
import random
import string
from typing import Any, Dict

from .config_models import TimeSlotConfig


CUSTOMER_NAMES = [
    "Ana Torres",
    "Carlos Ruiz",
    "Laura Diaz",
    "Juan Perez",
    "Maria Gomez",
]

DOCUMENT_TYPES = [
    "invoice",
    "receipt",
    "report",
    "claim",
    "evidence",
    "metadata",
]

CITIES = [
    "Bogota",
    "Medellin",
    "Cali",
    "Barranquilla",
    "Bucaramanga",
]

COMMENTS = [
    "Synthetic event for thesis MVP.",
    "Generated for statistical and probability analysis.",
    "Structured content for dataset-first simulation.",
    "Logical content generated by the simulator.",
]


def random_nonce(length: int = 16) -> str:
    """Generate a random alphanumeric nonce."""

    alphabet = string.ascii_letters + string.digits
    return "".join(random.choice(alphabet) for _ in range(length))


def random_datetime_in_slot(
    base_date: datetime,
    time_slot: TimeSlotConfig,
) -> datetime:
    """Generate a random datetime inside a configured time slot."""

    start_hour, start_minute = map(int, time_slot.start.split(":"))
    end_hour, end_minute = map(int, time_slot.end.split(":"))

    start_dt = base_date.replace(
        hour=start_hour,
        minute=start_minute,
        second=0,
        microsecond=0,
    )

    end_dt = base_date.replace(
        hour=end_hour,
        minute=end_minute,
        second=59,
        microsecond=0,
    )

    total_seconds = int((end_dt - start_dt).total_seconds())

    if total_seconds < 0:
        raise ValueError(
            f"Invalid time slot: {time_slot.start} - {time_slot.end}"
        )

    return start_dt + timedelta(seconds=random.randint(0, total_seconds))


def compute_content_hash(payload: Dict[str, Any]) -> str:
    """Compute a deterministic SHA-256 hash from a canonical payload."""

    canonical = json.dumps(payload, sort_keys=True, ensure_ascii=False)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def split_hash(
    content_hash: str,
    head_length: int,
    tail_length: int,
) -> tuple[str, str]:
    """Return head and tail segments from a content hash."""

    if head_length <= 0:
        raise ValueError("head_length must be greater than 0.")

    if tail_length <= 0:
        raise ValueError("tail_length must be greater than 0.")

    if head_length + tail_length > len(content_hash):
        raise ValueError(
            "head_length + tail_length cannot exceed content hash length."
        )

    return content_hash[:head_length], content_hash[-tail_length:]


def build_logical_payload(
    simulation_date: str,
    sequence: int,
    file_type: str,
    time_slot: TimeSlotConfig | None = None,
) -> Dict[str, Any]:
    """Build a logical payload used only for dataset simulation.

    This payload is not written to disk by the simulator. It only provides
    deterministic content for hash generation and traceability.
    """

    base_dt = datetime.fromisoformat(simulation_date)

    if time_slot is not None:
        event_dt = random_datetime_in_slot(base_dt, time_slot)
        time_slot_name = time_slot.name
    else:
        event_dt = base_dt + timedelta(minutes=random.randint(0, 1439))
        time_slot_name = None

    return {
        "logical_content_id": f"CONTENT-{base_dt.strftime('%Y%m%d')}-{sequence:06d}",
        "file_type": file_type,
        "document_type": random.choice(DOCUMENT_TYPES),
        "customer_name": random.choice(CUSTOMER_NAMES),
        "city": random.choice(CITIES),
        "amount": round(random.uniform(50.0, 5000.0), 2),
        "logical_creation_datetime": event_dt.isoformat(),
        "day_of_week": event_dt.strftime("%A").lower(),
        "time_slot": time_slot_name,
        "comment": random.choice(COMMENTS),
        "nonce": random_nonce(),
    }


def build_content_signature(
    payload: Dict[str, Any],
    head_length: int,
    tail_length: int,
) -> Dict[str, str]:
    """Build hash-derived fields for the dataset."""

    content_hash = compute_content_hash(payload)
    hash_head, hash_tail = split_hash(
        content_hash=content_hash,
        head_length=head_length,
        tail_length=tail_length,
    )

    return {
        "content_hash": content_hash,
        "hash_head": hash_head,
        "hash_tail": hash_tail,
    }